version: '3.4'

services:
  tv_chat:
    # image: tv_chat
    tty: true
    # stdin_open: true
    ports:
      - 8080:80
    build:
      context: ./images/tv_chat
    volumes: 
      - ${APP_PATH}:/usr/app/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_STRING=${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/tv_chat
  db:
    tty: true
    # stdin_open: true
    ports:
      - 3306:3306
    # build:
    #   context: ./images/db
    # image: mcr.microsoft.com/windows/servercore:ltsc2022
    image: mariadb:latest
    volumes: 
    #   - type: bind
    #     source: unbound
    #     target: C:/data/
      # - .\data\db\:C:\mariadb\data\
      - db_data:/var/lib/mysql
      # - ./data/db/:C:/Program Files/MySQL/data/

    # image:  mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u ${DB_USER} -p${DB_PASSWORD} --silent']
      interval: 3s
      retries: 5
      # start_period: 30s
    # volumes:
    # - db-data:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: tv_chat
    #   - MARIADB_ROOT_PASSWORD=root
    # expose:
    #   - 3306

volumes:
  db_data:
    # external: true